spring:
  h2:
    console:
      enabled: true
  datasource:
    platform: h2
    url: jdbc:h2:~/testdb
    driverClassName: org.h2.Driver
    data-username: sa
    data-password:
  flyway:
    url: jdbc:h2:~/testdb
    user: sa

datasource:
  tableName: "Task_definition"
  mirrorTableName: "Task_definition_mirror"
